### ISSUE TITLE
[v2.0.0]Puppeteer/パペッティア

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#1]
陣営：インポスター  
判定：インポスター

- [ ] キルした対象に、対象が次に近づいたクルーをキルさせる。
- [ ] 対象がBaitだった場合は能力が発動せず普通のキルになり、対象がキルした相手がBaitだった場合は対象の名前でセルフレポートされる。
対象がBaitだった場合を除き普通のキルを行うことはできない。

**Comment by Palpunte-Soukun** [comment]
対象がBaitであっても、通常キルを行うことはできない
