### ISSUE TITLE
not working on cell phones 

### ISSUE THREAD

**Issue by Dxgamer7405** [tukasa0001/TownOfHost#1031]
You yourself say that only the host needs to have the mod, but that's not what's happening, the game has a black screen on the phone

**Comment by Tommy-XL** [comment]
The black screen is due to the fact that one of the players crashes out of the game due to an error

**Comment by Tommy-XL** [comment]
You need to start the game so that during the beginning no one flew out

**Comment by Dxgamer7405** [comment]
> The black screen is due to the fact that one of the players crashes out of the game due to an error

I literally waited like 2 minutes and nothing happened

**Comment by yurinakira** [comment]
https://github.com/tukasa0001/TownOfHost/issues/903
