### ISSUE TITLE
new imp rol;e idea

### ISSUE THREAD

**Issue by Duckposter** [tukasa0001/TownOfHost#1038]
Role: Eraser
Team: Impostor
Description: Erase them all
Eraser can erase a dead body when press kill button on it but he can't erase his kills(work with your teammate)
![Eraser](https://user-images.githubusercontent.com/110590501/186593124-d9ada423-eae3-48a2-b834-d7eadd70dddb.png)

**Comment by BornBasic** [comment]
> Role: Eraser
> Team: Impostor
> Description: Erase them all
> Eraser can erase a dead body when press kill button on it but he can't erase his kills(work with your teammate)
> ![Eraser](https://user-images.githubusercontent.com/110590501/186593124-d9ada423-eae3-48a2-b834-d7eadd70dddb.png)
> 

Maybe use the shapeshift button to erase body?

**Comment by radian462** [comment]
I'm sorry, but we can't make the body disappear at this stage.

**Comment by Tommy-XL** [comment]
In this mod, you cannot make a corpse disappear, since such a mechanic with the interaction of a corpse has not yet been done in the game itself

**Comment by yurinakira** [comment]
>Eraser
死体は途中で消せません。
#903 を見てください。
