### ISSUE TITLE
Stopping supporting TChinese Traslations at 8/30(if have BIG update i will try to make traslations)

### ISSUE THREAD

**Issue by NetherDragonTw** [tukasa0001/TownOfHost#1046]
Reason are there:
1. i must go to school, so i don't have many time
2. using the git to make traslations is very hard from a dev noob, dev noob can't learn mosty command and can't solve some problem.
3. there is many people try to copy and add self traslations and make a PR to make steal someone's work and make it's self.

**Comment by yurinakira** [comment]
Trans
理由があります：

私は学校に行かなければならないので、あまり時間がありません
git を使用して翻訳を行うことは、開発初心者にとって非常に困難です。開発初心者はほとんどのコマンドを学習できず、いくつかの問題を解決できません。
他人の作品を盗用して自分のものにするために、自己訳文をコピーして追加し、PR を作成しようとする人がたくさんいます。

**Comment by yurinakira** [comment]
understood. Thank you for what you have done.
