### ISSUE TITLE
Randomly getting kicked/disconnecting

### ISSUE THREAD

**Issue by The-LaughingMan** [tukasa0001/TownOfHost#1101]
Whether im in another modded game (with the same mod as mine) or jus tplaying normal. ill get the message saying "you've been kicked "  even though i know they didnt vote kick me.  It can happen anytime in game.

But to everyone else it just says i left.  whats causing this?

**Comment by tampopo-dandelion** [comment]
The issue pages are not used. Please use our discord server.

**Comment by yurinakira** [comment]
another modded?
I'm embarrassed if you ask me anything unrelated to our mod.

**Comment by The-LaughingMan** [comment]
Obviously you didnt fully read my comment Yurinakira...try again. see the brackets?
