### ISSUE TITLE
Neutral Chaos role idea

### ISSUE THREAD

**Issue by Duckposter** [tukasa0001/TownOfHost#1177]
so we actually have Neu Benign Neu Evil and Neu Killing role but what about make someting Chaotic?
new role idea: Infector
Team:Neutral(Chaos)
Basis:Impostor
Victory Condition: Infrect everyone
Infector is role based on Arsonist he can change player role on Infected when atack them. Infected players know who is Infector but not know who is other infected. When Infector try to kill a Impostor or other Neutral Killing role he just kill player. When Infector was Ejected/Killed every Infected player change roles.
When Infector infect enough players(limit reached) his convert stop work and he can't convert/kill not a Imp/NK roles(still can kill if target can't be converted)
Options:
Infector Infect Cooldown (1 - 999)
when Infector die Infected change role on: (Crewmate or Opportunist)
Infected player know who is Infector (Yes or No)
Infected Players Limit(1-15)
also new Sheriff opti
![Infector](https://user-images.githubusercontent.com/110590501/192751237-78a61481-6d95-40c3-8817-1c3ba0770622.jpg)
ons:
Sheriff can kill Infector (Yes or no)
Sheriff can kill Infected (Yes or no)

**Comment by soukunsandesu** [comment]
Not support issue.
Join discord server.

**Comment by soukunsandesu** [comment]
But, we will reject this suggestion.
