### ISSUE TITLE
会議で追放された次のターンのみ幽霊で壁をすり抜けることができない（ジャッカルが入っている場合）

### ISSUE THREAD

**Issue by gengen0719** [tukasa0001/TownOfHost#1178]
いつも楽しく遊ばせていただいています。  
不具合と思われる動作を発見したので報告します。
  
- 問題  
会議で追放された次のターンのみ幽霊で壁やドアをすり抜けることができません。  
ハシゴの昇降やドア開けができないため、タスクの実施が困難になったり、  
サボタージュをうまく入れられなくなったりします。  
一度会議が入ると問題は発生しなくなります。
  
- 発生条件  
  - ジャッカルが入っていること(ジャッカルを入れた場合、抜いた場合で動作検証しました)  

- 確認したこと
     - ジャッカルの生存有無に関わらず発生しました  
     - ホストかどうかに関わらず発生しました  
     - Modの利用有無に関わらず発生しました

- AmongUsのバージョン
v2022.9.20s(2295)

- TownOfHostのバージョン
v3.0.1

**Comment by soukunsandesu** [comment]
Discordサーバーのバグ報告チケットへお願いします
