### ISSUE TITLE
Mod causes a black screen with the game startup

### ISSUE THREAD

**Issue by just-matsuki** [tukasa0001/TownOfHost#1188]
# Mod makes the game keeps showing a black screen 
--- 
I did update the game today 'n tried to play but kept getting stuck at a black screen (after seeing the Innersloth animation and new loading animation), I did try deleting the game 'n adding the mod again but the same issue, decided to try the game without the mod 'n it worked normally. so, I suppose the mod has a conflict with the new game update files 

### Without the mod 
![image](https://user-images.githubusercontent.com/66541630/197768756-170f831a-0f2d-4ad3-abbd-42e7588363c0.png)

### With the mod 
![image](https://user-images.githubusercontent.com/66541630/197768715-10bf00a9-9f38-4792-a041-c48c2d40317a.png)

I did try restarting the device as well 'n all the basic solutions

@tukasa0001 @mii-47 @ykundesu @tanakanira0118 @soukunsandesu (sorry for the massive mention for you all, hope I didn't disturb your peace in any form, thanks!)

**Comment by tanakanira0118** [comment]
We are sorry.
We do not provide support on the Issue page.
Please join our Discord server and ask your question in the help channel.
