### ISSUE TITLE
Add my German Translation in my Lobby

### ISSUE THREAD

**Issue by Sharalis** [tukasa0001/TownOfHost#1233]
Hey =)

**At first, i love you Mod! Its gorgeous to play with all these rolles. Thanks for the opportunity.**

Now for my request.
I have no problems with english language, but im a german player and so on, many players in my Lobby will be young german player with issues in this. At the time, i exlplaind all importens rolls mannuel per copy&paste in the first meeting, but this is really annoying.
I had read the instructions for customiz my one template. But is don't know, how i can bring it in my game?

> In the file, enter like before translation:after translation.

    For example: Command.rename:Change Host Name
    See template.dat for the before translation string.<

I dont understand which file is mean. My translation file? A programm file? Maybe i have to send the translation to you?
Can you help me out? Dicord is no help, because I dont finde the right channel.

Thank from me =) Have a nive X-Mas time.

**Comment by BornBasic** [comment]
Go to Language folder. You can see a file named template_English.dat You can easily open the file with Notepad. Now do your own language translation in this file. Just follow the template. Your translation should always after the " : " . After that, save the file as "German.dat" .

**Comment by Sharalis** [comment]
Haha so simple xD Now I see my mistake. Its was a simple translation issue from poor me. Thanks for this =)
