### ISSUE TITLE
The bugs of TOH401

### ISSUE THREAD

**Issue by SCPB127Guard** [tukasa0001/TownOfHost#1234]
**Bugs**
1.Sometimes Camouflage is still happening after communication fix.
2.Cat can't see killer and killer's teammates(like impostor), killer and killer's teammates also can't see cat.(killer often kill cat again because killer don't know cat join its team)
3.If Impostor and Jackal are lovers, when they kill all the other roles, they don't win.
**my ideas**
1.Every impostor can see the roles of their teammates
2.Lovers can see the roles of their lover.
3.Sidekickis assigned to the player as a roles so Jackal don't need Create A Sidekick.

**Comment by Sharalis** [comment]
More Bugs

- Lovers can destroy your role. You have no tasks anymore (really annoying when you are Snitch and Lover)

**Comment by Sharalis** [comment]
and more =)

- Sheriff and Arsonist can Sabotage when play on not modded Client (this sucks ...)

**Comment by ybogasyad** [comment]
And ping!! unless its just me. its constantly steadily up and down, 60ms-6000ms. It often kills the server too.

**Comment by Sharalis** [comment]
I thinks the problem with discord is, they is no english treat for this. I din't found any ... But i will search and if I find any, I will tell you =(

**Comment by Sharalis** [comment]
> and more if lover die, another one should die too, but sometimes if lover die, another can't die. And another one will enter the ghost (It will go through the walls,but it's alive, It can still speak, and do task,vote,vent,kill)
> 
> more idea Start role show: Show the true roles, not neutrals roles and madmates roles are engineers. Impostor roles are shapeshifters, and crewmates roles are crewmates.(It's not good for players if they first play this mod,they will shout on first meeting like:"I'm engineer!" "How to play terrorist?" "Why I can't see my impostor teammate?'' ''I'm real engineer because Start role show me it!'' I can't stand such stupid questions, please fix it)

I thinks this is because of the discription. I wrote my on translation and let them know per /m no what is the issue. We mdae first meeting every round, so they can understand there role. And all they can't read or understand ... you don't need this player in your lobby xD

**Comment by Sharalis** [comment]
> > > and more if lover die, another one should die too, but sometimes if lover die, another can't die. And another one will enter the ghost (It will go through the walls,but it's alive, It can still speak, and do task,vote,vent,kill)
> > > more idea Start role show: Show the true roles, not neutrals roles and madmates roles are engineers. Impostor roles are shapeshifters, and crewmates roles are crewmates.(It's not good for players if they first play this mod,they will shout on first meeting like:"I'm engineer!" "How to play terrorist?" "Why I can't see my impostor teammate?'' ''I'm real engineer because Start role show me it!'' I can't stand such stupid questions, please fix it)
> > 
> > 
> > I thinks this is because of the discription. I wrote my own translation and let them know per /m what is the issue. We made first meeting every round, so they can understand there role. And all who can't read or understand ... you don't need this player in your lobby xD
> > For Snitch I wrote: NEVER out your Role. NEVER! and for Terroist: Your aren't an engineer, but you can vent. Its annoying i know, but i think this is this price, becauce we can play with no modded clients. Let them know in the discription und hope the best =)
> 
> thanks, I'm not English or American,So I use machine translation, my English grammar is not good, please forgive me if you don't understand

If you are germanm, I can help you better =)
