### ISSUE TITLE
模组文件损坏，请重新安装本模组

### ISSUE THREAD

**Issue by haokaixin21** [tukasa0001/TownOfHost#1238]
您好，我在使用您的模组的时候，出现错误提示，模组文件损坏，请重新安装本模组，但是我重新安装后还是不能正常游戏，重装电脑也不可以，只能更换新的steam才可以，但是过1天后又会弹出这个提示，想问一下，怎么修复这个bug，谢谢您。
![bug1](https://user-images.githubusercontent.com/119652602/211579423-f351a74e-3bff-4884-9b7e-cdea099f0b45.png)
![bug](https://user-images.githubusercontent.com/119652602/211579473-4658d1dd-8690-4ecc-a4c6-0ffa43bcad7d.png)

**Comment by haokaixin21** [comment]
This is a machine translation version, which may not quite correspond to normal speaking logic, thanks for understanding
Hello, when I use your mod, there is an error message, the module file is damaged, please reinstall this module, but I still can't play normally after reinstalling, reinstalling the computer can't be, you can only replace the new steam, but after 1 day will pop up this prompt, want to ask, how to fix this bug, thank you.

**Comment by yurinakira** [comment]
Please install again from vanilla.  We do not accept questions here.

**Comment by KARPED1EM** [comment]
兄弟，我第一次用C语言，可能没看得很仔细，但这个似乎是因为检查更新的时候发生错误造成的

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/212634222-a9096056-1183-4223-a204-aaadd3272bbb.png)

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/212634451-25aa384e-6ffd-4054-aede-a2ebab1f9fac.png)

**Comment by yurinakira** [comment]
Turning off the check function without knowing the cause is a third-rate thing to do.
Turning off the check function without knowing the cause is a third-rate thing to do.
If it only happens in your environment, installing from vanilla state from scratch will not cause any problems. that's all. We do not answer questions on issues. good bye.

**Comment by haokaixin21** [comment]
No, I tried reinstalling, reinstalling the system, changing steam, turning on accelerators, etc., but they couldn't recover, so I posted a help

**Comment by haokaixin21** [comment]
Moreover, you said that my check for updates feature is turned off because I am in China and cannot connect to github all the time

**Comment by KARPED1EM** [comment]
> 在不知道原因的情况下关闭检查功能是三流的事情。 如果它只发生在您的环境中，从头开始从原始状态安装不会导致任何问题。就这样。我们不回答有关问题的问题。再见。

我对于试图用关闭更新检查来解决问题感到非常抱歉。
但是由于许多位于中国的用户无法正常连接Github，大部分中国用户并不懂得代码之类的东西，也无法绕过GFW的限制。
通过关闭更新检查临时解决该问题对中国来说并没有很过分吧？

我知道这样敷衍的解决方案不适合发布在Github。但我也只是想用最简单的方式解决最普通的中国用户的问题。仅此而已。

很感谢TOH制作组提供了宝贵的意见和支持。接下来我们会尝试自己解决这个问题。打扰到你们真的很抱歉。

**Comment by yurinakira** [comment]
We access github with the version check function, but we have confirmed that this kind of phenomenon occurs for users who cannot access github (mainly Chinese people, I think).
It's not currently a bug.
In the next update, if it is "Chinese PC and Chinese", we are considering not checking it.

**Comment by qwqZYLqwq** [comment]
这个问题我也遇到过很多次，目前我认为最好的解决方法是重新上线steam好友，或者开加速器基本就不会再出现问题了
