### ISSUE TITLE
MOD file damaged (v4.0.2)

### ISSUE THREAD

**Issue by KARPED1EM** [tukasa0001/TownOfHost#1239]
It shows "**The MOD file is damaged. Please reinstall**" at main menu and lobby.
btw, I CAN NOT publish my lobby, and I even CAN NOT join games form others.
**I tried reinstall and restart my PC, it still dosen't work.**
A lot of my firends have this problem too, so that we can't play TOH recently. : (

**Comment by KARPED1EM** [comment]
![img1](https://user-images.githubusercontent.com/89320463/211896547-d1263f77-ec47-4073-9f59-3b6a9404a363.png)
![img2](https://user-images.githubusercontent.com/89320463/211896550-85ce3661-2370-4779-87da-b29fe2b602dc.png)

**Comment by KARPED1EM** [comment]
ill upload log file tomorrow
Thank you so much for your work, i really love this mod
fix it PLEASE

**Comment by KARPED1EM** [comment]
Oh I just saw Dsicord now. my bad
I'll be looking for help on discord

**Comment by yurinakira** [comment]
Please install again from vanilla.  We do not accept questions here.

**Comment by haokaixin21** [comment]
No, I also have this problem, but tried to reinstall, reinstall the system, reinstall steam, replace with new steam, all invalid, this problem, many of my friends have appeared, please officially fix this bug, or tell us the solution

**Comment by Saintora** [comment]
> No, I also have this problem, but tried to reinstall, reinstall the system, reinstall steam, replace with new steam, all invalid, this problem, many of my friends have appeared, please officially fix this bug, or tell us the solution

Use mod manager to install mod  but.

**Comment by yurinakira** [comment]
We access github with the version check function, but we have confirmed that this kind of phenomenon occurs for users who cannot access github (mainly Chinese people, I think).
It's not currently a bug.
In the next update, if it is "Chinese PC and Chinese", we are considering not checking it.
