### ISSUE TITLE
推奨事項

### ISSUE THREAD

**Issue by InvincibleFool** [tukasa0001/TownOfHost#1259]
In the next version, players who have used TOH (TOR) will be reminded to use "casual" when creating rooms, and the broadcast when entering will remind players that "the next version of TOH (TOR) can only be found in the casual category"

In the next version, players using TOH (TOR) can only create rooms under the "casual" category

I can't even find a room without TOH (TOR) in the Chinese room
So I hope to take my opinion

sure,I also released this suggestion under other TOH branches

**Comment by KARPED1EM** [comment]
what about ask Innersloth for this

**Comment by InvincibleFool** [comment]
> 问问因纳斯洛斯怎么样

don't BB,you need do it too[滑稽]

**Comment by yurinakira** [comment]
https://github.com/tukasa0001/TownOfHost/issues/1242
