### ISSUE TITLE
Put String file to work in my lobby

### ISSUE THREAD

**Issue by AirConditionunit** [tukasa0001/TownOfHost#1263]
i edited the string file and edited some messages to roles at start like doctor to be "See cause of death of bodys" it didnt work how do i make it work? (also i have no discord so plz reply) 

So better said: the string file has the /m command to all commands i want to be able to change it... how do i do it?

**Comment by KARPED1EM** [comment]
what u use to edit csv file?
dnspy or something?

**Comment by BornBasic** [comment]
if you are editing the Languange folder. Rename your file to English.dat

**Comment by KARPED1EM** [comment]
oh i thought you edit the csv file.
to use the language file just rename that file to English.dat first

**Comment by KARPED1EM** [comment]
`..\Among Us\TOH_DATA\Language/English.dat`
this file?

**Comment by KARPED1EM** [comment]
> Quick Question: what does the Setting Role assigning Algorithm do?

Way to get random numbers used to assign roles to players
