### ISSUE TITLE
Other stuff

### ISSUE THREAD

**Issue by AirConditionunit** [tukasa0001/TownOfHost#1264]
{Deleted by author of message}

**Comment by NetherDragonTw** [comment]
sup bro there is a new discord link https://discord.gg/pGX9uxFV

**Comment by BornBasic** [comment]
There is English category. Please go through the channels before commenting here

**Comment by yurinakira** [comment]
#general
https://discord.com/channels/931559416413687848/995761289529925742

#help
https://discord.com/channels/931559416413687848/995761451102904500

**Comment by yurinakira** [comment]
If you can't move to the link above, I think it's because you haven't read and accepted the rules.

#rule 
https://discord.com/channels/931559416413687848/931780629450866688/931784784546512946

**Comment by yurinakira** [comment]
Please close the issue if there is no problem.

**Comment by yurinakira** [comment]
I want you to follow the rules...
We only accept questions on Discord.

You wrote and explained how to get to the English channel on Discord, but you're going to ignore it?

There is no problem if the language file absorbs the difference.

**Comment by yurinakira** [comment]
I think you should try discord as an app or web browser. If you can't use either, I recommend buying a new PC.
