### ISSUE TITLE
Game Room

### ISSUE THREAD

**Issue by CNFlorin1** [tukasa0001/TownOfHost#1297]
Players cant see my room, they enter just with the code

**Comment by Slok7565** [comment]
Oh Gosh, Because Of InnerSloth, All Host Mods Juse Can Be Entered By Code

**Comment by JakeHumter** [comment]
As yurino(mod at discord) said at 07/15/2023 12:32 PM

About the problem that the created public room does not appear in the room search
I got a call from innersloth.

"Currently, a vanilla user unintentionally enters a mod room,
cause user confusion,
As the number of official inquiries is increasing,
It prevents vanilla users from entering mod rooms unintentionally.

We plan to allow mod rooms to be filtered in an update to the search filter.

Until then, please publish the room code in the community( ⁠match-making ) of each mod and play. ”

**Comment by yurinakira** [comment]
That's everything written above.
It's not a problem, and Discord is the only place to deal with the issue, so I'll close it.
