### ISSUE TITLE
背信者

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#13]
陣営：妖狐
判定：未定

妖狐の味方となるプレイヤー
妖狐がわかる以外特殊能力はない。
~~v2021.12.15時点で実装不可能~~

**Comment by shu-TownofHost** [comment]
名前革命によって妖狐の名前に色をつけて通知することが可能になったのでおそらく可能

**Comment by tukasa0001** [comment]
まだ妖狐の実装も未定な状態なので、一度クローズします。
