### ISSUE TITLE
Submerged停電モード

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#14]
停電をチカチカ⇒狭い視野になるように変更するモード

**Comment by tanakanira0118** [comment]
多分これある程度小刻みにRPCを送る必要があるので、Switch等のコンシューマー機が死にます

**Comment by Palpunte-Soukun** [comment]
停電発生時にカチカチ　=> 一定時間経つまで視界0、LateTaskで数秒後に視界を普通の停電のものに戻す

これでいけるんじゃないかと

**Comment by tukasa0001** [comment]
SyncSettingsRpcを小刻みに送ると重そうなので没
