### ISSUE TITLE
Ramdom-cooldown

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#17]
会議毎にキルクールダウンを指定範囲内でランダムに変更するモード
一秒単位でランダム化される。

**Comment by Palpunte-Soukun** [comment]
ウォッチャーの陣営抽選を会議ごとに挟めばOK

**Comment by tukasa0001** [comment]
使い道がなさそうなので没。
そもそも役職割り当て以外のゲーム進行に関わる処理にあまり乱数を絡ませたくない。
