### ISSUE TITLE
Victory Changes

### ISSUE THREAD

**Issue by SkullCreeper** [tukasa0001/TownOfHost#627]
English: A change to how end screens work. Currently, vanilla clients don't win when it's not a Crewmate win. Madmates currently win with crewmates for vanilla clients, and this needs to change along with other roles such as Arsonist. 
My suggestion is to make it so whether its not a crewmate victory, make the winners be impostors and the losers crewmates. This would make madmates win with impostors on vanilla clients. If it's a Lovers win, the Lovers turn into Impostors and everyone else becomes crewmate so only the lovers appear on the end screen. I've seen many Madmates exile the Impostors because for them, they win with the crewmates, which ruins the point.
I am using Google Translate so I am sorry if there are errors with grammar.

Japanese: 終了画面の操作方法を変更します。 現在、乗組員が勝たない限り、バニラクライアントは勝ちません。 マッドメイトはバニラクライアントクルーメイトで勝ちます。 これは、放火犯などの他の役割とともに変更する必要があります。
私の提案は、たとえそれが乗組員の勝利でなくても、勝者を詐欺師にし、敗者を乗組員にすることです。 これにより、Madmatesはバニラクライアントの詐欺師を打ち負かすことができます。 恋人の勝利なら、恋人は詐欺師になり、他の全員は乗組員になるので、最後の画面には恋人だけが表示されます。 私は多くの狂人が詐欺師を追放するのを見てきました。 彼らにとって、彼らは彼らの乗組員に勝ち、彼らのポイントを台無しにします。
私はGoogle翻訳を使用しているので、文法上の誤りがあった場合は申し訳ありません。

To all you English speakers, why does Impostor translate to Scammer lol

**Comment by shu-TownofHost** [comment]
Excuse my message.
Unfortunately, the current technology does not allow us to change the imposter during the match. As an exception, only guardian angels can change their position.
I would like to fix the vanilla client's mad mate being visible during the crew win, but the only way to do it now is to make the decision imposter from the original.
Someday when the position is changed, the winner will be an imposter and the win decision will be improved.
Also, this is using a translation so there may be grammatical errors.
