### ISSUE TITLE
Possible way to guess roles

### ISSUE THREAD

**Issue by Tommy-XL** [tukasa0001/TownOfHost#630]
Is it possible for traitors in this mod to implement the function of guessing roles through the general chat? (For example: "/role (Nickname) Jester" )
After all, there are a lot of roles in the new version, but at the same time, other players freely talk about their role in voting

**Comment by shu-TownofHost** [comment]
It is possible, but the executed chat command cannot be erased and the executor will be exposed. Therefore, a position like that of a gesser in TheotherRoles cannot be implemented at this time.
