### ISSUE TITLE
Arthonistの対象者

### ISSUE THREAD

**Issue by jckkvs** [tukasa0001/TownOfHost#679]
オイルを塗っていない相手が吊られた場合、その相手にオイルを塗ることができなくなり勝利できなくなる仕様になっていますか？

**Comment by soukunsandesu** [comment]
Fixed in this version
https://github.com/tukasa0001/TownOfHost/releases/tag/v2.0.3

**Comment by jckkvs** [comment]
V2.0.3で1キル、１吊りの状態で検証しましたが、アーソニストがベントに入れませんでした。

メンバー7人：スケルド

**Comment by soukunsandesu** [comment]
Sorry, Fix in next version…
