### ISSUE TITLE
add support for 2022.4.19

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [tukasa0001/TownOfHost#690]
i wanna play this mod but i cannot

**Comment by Tommy-XL** [comment]
Perhaps you need to remove the Beta version of the game, because the latest release version of the game is v2022.3.29s

**Comment by shu-TownofHost** [comment]
I can't answer your question without more details....
Which version specifically is impossible?
What do you mean it is not possible?
And so on.... I can't answer your question unless you write it down...
