### ISSUE TITLE
Arsonist bug / 放火犯のバグ

### ISSUE THREAD

**Issue by SkullCreeper** [tukasa0001/TownOfHost#696]
English: When a living, undoused player leaves, the arsonist cannot win.

日本語：生きている、使われていないプレーヤーが去るとき、放火犯は勝つことができません。
![image](https://user-images.githubusercontent.com/51543683/173374256-feb7b39d-86a5-43dd-a0c0-9f208a21dfde.png)
![image](https://user-images.githubusercontent.com/51543683/173373857-b2a535a8-f16f-492b-bc68-765c23a98c3f.png)
![image](https://user-images.githubusercontent.com/51543683/173373878-3d79db74-90c9-4685-9772-4e5d92019dc5.png)

**Comment by soukunsandesu** [comment]
That bug has been fixed in the development version. It will be update in the next update.
