### ISSUE TITLE
Custom hat

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#7]
# Custom Hat
その名の通り、カスタムハット機能。  
ただし、他のmodのカスタムハットと違い、バニラクライアントと共存することができる。  
プレイヤーはバニラハットと別にカスタムハットを装備することになる。  
カスタムハットはカスタムRPCで装備の処理がされ、バニラのハットとは完全に独立した処理となる。  
クライアント用modにより、カスタムハットをかぶっているプレイヤーのバニラハットは描画されず、カスタムハットのみが描画される状態となる。  
バニラクライアントからはそのような上書きはされず、バニラハットだけをかぶっている状態となる。  
ハットはファイル名によって管理される。  
# 確認事項
- [ ] バニラクライアントと共存してもバグが発生しない
- [ ] mod入りクライアントから見るとバニラハットが非表示になる
- [ ] mod入りクライアントから見ると正常にカスタムハットが適用される
- [ ] その他、カスタムRPCの送信タイミングなどに問題がない

**Comment by soukunsandesu** [comment]
これどうすんの

**Comment by tukasa0001** [comment]
TOHの最大の特色はバニラと共存し、拡張できることであり、そこにmodクライアント限定の装備品を追加してしまうと、mod,バニラ間でのコミュニケーション上の壁になってしまうという懸念があるため没。

本音を言いたいところですが、可燃性があるのでそっと廃棄しておきます。
