### ISSUE TITLE
Adding Nice Guesser and Evil Guesser

### ISSUE THREAD

**Issue by Tommy-XL** [tukasa0001/TownOfHost#703]
(If that was used by the translator, so there are errors in the text)

I also want to discuss the idea of ​​"Guessers" in fashion, during the game sometimes people calmly talk about their role, but when a moment happens that a peaceful and a traitor argue among themselves and vote for each other, the peaceful one begins to defend himself and talks about his own role, and  the rest begin to believe in her and vote for the impostor. But what if the role of the guesser is still added to the game, but with the condition that after guessing the role, they will immediately understand who is the guesser in this game (after all, the traitor does not have to guess the players at the very beginning of the game, he can do it at the moment when  the rest are already sure that you are a traitor and at this moment you can try to guess people, and also the players cannot know for sure that there is a guesser in this game, but they are in no hurry to reveal their role because they don't know for sure if there is a guesser in the game)  For the lobby host, you can make your own guessing interface like in The Other Roles mod, and for the non-host player, the lobby will guess the roles using the general chat (for example: /role (player position or Nickname) Jester)

I hope you will heed my own suggestion to add guessing roles to the mod

**Comment by firefoxnightlymozzila** [comment]
im just going to add this but in order to guess people on unmodded clients they could type something like /guess (role name) (player name / color)

**Comment by soukunsandesu** [comment]
creating

**Comment by Tommy-XL** [comment]
次のバージョンには"Nice-Evil Guesser"という新しい役割があるのは本当ですか？

Will there be a next version with the role of "Nice-evil Guesser"?

**Comment by tampopo-dandelion** [comment]
I don't know if it will be implemented in the next version, but it is currently being adjusted. Please wait a moment.
