### ISSUE TITLE
Camouflaged communications / カモフラージュされた通信

### ISSUE THREAD

**Issue by SkullCreeper** [tukasa0001/TownOfHost#707]
English: To put it simply, camouflaged communications turns everyone gray without names or cosmetics. This would make the communications more powerful as then it'd be a bad idea to report a body during the sabotage, as meetings would also be camouflaged.

日本：簡単に言えば、カモフラージュされたコミュニケーションは、名前や化粧品なしですべての人を灰色にします。 これにより、コミュニケーションがより強力になります。会議もカモフラージュされるため、妨害中に遺体を報告することはお勧めできません。

**Comment by soukunsandesu** [comment]
We trying it, but we don't intend for the meeting to be camouflaged either.

**Comment by tampopo-dandelion** [comment]
Rpcshapeshiftなしでできるんですかねこれ

**Comment by soukunsandesu** [comment]
既存のRpcShapeshiftは使わずに作る
