### ISSUE TITLE
Color command / カラーコマンド

### ISSUE THREAD

**Issue by SkullCreeper** [tukasa0001/TownOfHost#708]
English: A command that lets you be any color in the game. Useful to eliminate color fights.

日本：ゲーム内で任意の色にできるコマンド。 色の戦いを排除するのに便利です。
![image](https://user-images.githubusercontent.com/51543683/173880459-1cf307eb-d2e7-4071-a960-b64c1b1bcd97.png)

**Comment by soukunsandesu** [comment]
不要かと
