### ISSUE TITLE
Role suggestion「Identity-Scanner」

### ISSUE THREAD

**Issue by AllawiEZ** [tukasa0001/TownOfHost#735]
Role: Identity-Scanner
Team: Crewmate
Ability:
1-For normal among us launcher: When loading in the game, The player with the role will have an "Fake impostor" like the arsonist/sheriff loading screen but after loading it will say Identity-Scanner (player). he can't vent or sabotage but when he use the kill button he will reveal the role of the player.

2-For town-of-host launcher: When loading in the game, The player with the role will have a crewmate a loading screen. When loading it will say Identity-Scanner with description "Discover players roles." He will have a button that when clicked he will reveal player's role.

Extra settings:
1-Who can see revealed players role: (Everyone/player+identity-scanner/identity-scanner)
2-Scan cool-down: (Default 45 seconds)
3-Amount of scans: (Max scans: 5) (So it will be fair.)

**Comment by soukunsandesu** [comment]
占いみたいなものですね

**Comment by AllawiEZ** [comment]
> 占いみたいなものですね

リンクに（未定）なしで（新しい役職）を追加することは、それが来ることを意味しますか？

**Comment by soukunsandesu** [comment]
つけ忘れです…
