### ISSUE TITLE
Role suggestion [Guessers]

### ISSUE THREAD

**Issue by AllawiEZ** [tukasa0001/TownOfHost#746]
Hello developers,
A role which you can guess people's roles in meetings!

Among us standard launcher: type in chat /guess (role name) (player's name/color) and they will die but people can't see the command they typed like /template test one. If that dosen't work i recommend clearing chat and post (The guesser has guessed someone) and post the last 3 messages

Town of host launcher: a target icon on their head if the icon is clicked, There will be a menu full of roles to chose and guess the player's roles.

Additional settings:
Max amount of guesses: (Default) 4
Chance of guesser to be evil: (Default) 0%
Reveal the guessed player's role after getting guessed: off/on

**Comment by soukunsandesu** [comment]
please read closed issue

**Comment by AllawiEZ** [comment]
> please read closed issue
I'm still thinking of saving the last 3 messages and fulling the chat with messages so it will be cleared it will post last 3 messages and then say "The guesser has took a shot!". If that is not possible im sorry for being annoying.

**Comment by soukunsandesu** [comment]
Sorry, sent message can’t change.
