### ISSUE TITLE
Role Suggestion Jackal

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [tukasa0001/TownOfHost#760]
The Jackal is a neutral role who's goal is to kill EVERYONE (even impostors) and be the last player standing
The Jackal can be killed by impostors
A player can be requited to be the Sidekick (sidekick see's who their teammates are and his goal is to help the jackal win (like madmate but it can see the teammate The requiting is done via a shapeshift and if the target is close enough it will requite them (the jackal cannot remain shifted nor shift again as it is only to requite a player if the requited player is a impostor they still appear as a impostor to their ex teammates
An optinal setting can be enabled to allow the Jackal to shapeshift (if disabled it's just a requit button)
Adittional settings...
Jackal kill cooldown
Jackal can create sidekick (on by default)
Jackal can shapeshift (if enabled shapeshift is more than a simple requit button) (off by default)
Jackal can vent (i will let the devs decide if this should be on by default)
Requited player keeps ability's (i will let the devs decide if this should be on by default)
Jackal can sabotage (off by default)
Jackal / Sidekick sabotage results in (impostor win) (Jackal win) (impostor by default)
NOTE: Jackal cannot sabotage by default
NOTE2: by default a requited player loses all their roles special ability's EXAMPLE: if the sheriff is requited the sheriff can no longer kill
NOTE3: If an impostor get's requited and Requited player keeps ability's is enabled a sabotage still results in a impostor win
NOTE4: the game will not end as long as the jackal is alive even in a scenario where the game would normally end due to impostors taking majority from non impostors say 2 impostors 1 crewmate and a jackal
NOTE5: even if all that is left is impostors and jackals the game will not end

**Comment by katzklaw** [comment]
i agree with AllawiEZ. i tried Egoist once, and then realized that it counts against the total count of impostors when checking against the win/loss vital numbers. i was hoping to use it to balance 3 imp games, but this doesn't help at all. i haven't played it since.

**Comment by Tommy-XL** [comment]
I also agree with the author, the role of the Egoist in the mod is meaningless, since he counts as a Traitor in the game but only with a different nickname color, the Jackal will add a more balanced game when there are 15 players in the game and 3 traitors with a jackal in the game, which in theory can kill traitors

**Comment by tampopo-dandelion** [comment]
jackal can not be solved the darkening in the current situation.so,jackal can not release in our mod.please close this issue.and at the next time, please ask us in our discord server.
but we will never give up to develop jackal! please wait for a while.

**Comment by Tommy-XL** [comment]
It's funny, but literally today they just recreated Jackal and she's being tested right now

**Comment by Tommy-XL** [comment]
#928

**Comment by soukunsandesu** [comment]
created
