### ISSUE TITLE
several bugs

### ISSUE THREAD

**Issue by katzklaw** [tukasa0001/TownOfHost#764]
1. Fireworks - as described can only kill normally after all fireworks are placed. in actual gameplay they can kill normally from the very start. .this makes this role incredibly OP
2. Mare - name appears red in meetings sometimes to some people. doesn't seem intentional?
3. Shapemaster - making use of the zero shift cooldown can possibly ban you
4. Time Thief  - doesn't seem to work at all
~~5. Sheriff - sometimes can see who imps are in meeting. sees their names as red~~
6. Speed Booster - doesn't appear to do anything.

~~7. the % does NOT mean what it does in vanilla, which is misleading, and i'm not sure is intentional. in vanilla it is however many of a role at whatever %. for example 3 engineers at 30% chance to get one each time. so it checks 3 times, with a 30% chance of each check being an engineer. in this mod, the % is "how much of the lobby % this role is". for example, if you set jester to 20% and you have a lobby of 10, 20% of 10 is 2. you will  ALWAYS have 2 jesters. no matter what. this completely eliminates random and seems unintentional.~~

**Comment by katzklaw** [comment]
i didn't mention the arsonist bug because i see that one has already been addressed

**Comment by soukunsandesu** [comment]
1 issue answer:
　fireworks can kill normally at start.
　fireworks start put fireworks, can’t kill normalcy.

sorry…

**Comment by soukunsandesu** [comment]
7 issue answer:
　CustomRole Chance doesn’t work. Please wait.

**Comment by katzklaw** [comment]
> 1 issue answer: 　fireworks can kill normally at start. 　fireworks start put fireworks, can’t kill normalcy.
> 
> sorry…

i can submit a video of killing normally as fireworks if i need to. but you can definitely kill via the kill button and not need to wait to plant explosives

**Comment by soukunsandesu** [comment]
``5. Sheriff - sometimes can see who imps are in meeting. sees their names as red``
Fixed

**Comment by soukunsandesu** [comment]
``4. Time Thief - doesn't seem to work at all``
Closed because it doesn't confirm.

**Comment by katzklaw** [comment]
> `4. Time Thief - doesn't seem to work at all` doesn't confirm.

time thief DOES work now.

**Comment by katzklaw** [comment]
> 7 issue answer: 　CustomRole Chance doesn’t work. Please wait.

i notice this section of my bug report is crossed out now. does that mean this is fixed internally and will be release soon?
