### ISSUE TITLE
Seer Role

### ISSUE THREAD

**Issue by 0xqr** [tukasa0001/TownOfHost#780]
It would be cool if there‘s a seer role that can review roles by clicking a button when near a player. There could be a customisable cooldown for the seer role. If someone gets revealed by the seer they see the seer themselves.

**Comment by AllawiEZ** [comment]
Already suggested
https://github.com/tukasa0001/TownOfHost/issues/735

**Comment by soukunsandesu** [comment]
Another Seer creating as things as The Other Roles mod!
