### ISSUE TITLE
Error message when I try to use the mod with Windows7

### ISSUE THREAD

**Issue by kushx1996** [tukasa0001/TownOfHost#794]
I have the latest version of AU from steam. I downloaded the latest version of mod i.e. 2.1.1. I extracted the zip file of the mod in a folder and also copied all local AU files and put them in the mod folder. Now when I run AU in that folder an error message pops up saying "A problem caused to stop the program run correctly. Please close the program." I use windows 7 ultimate. What do I do?

**Comment by firefoxnightlymozzila** [comment]
imagine using windows 7 in 2022

**Comment by AllawiEZ** [comment]
> I have the latest version of AU from steam. I downloaded the latest version of mod i.e. 2.1.1. I extracted the zip file of the mod in a folder and also copied all local AU files and put them in the mod folder. Now when I run AU in that folder an error message pops up saying "A problem caused to stop the program run correctly. Please close the program." I use windows 7 ultimate. What do I do?

This might be happening because of the mod folder being corrupted try making another among us file, run it then close it then put the mod folder back and run among us
If this doesn't work wait for new among us update to use the mod

**Comment by soukunsandesu** [comment]
If this mod doesn’t work, please update to Windows10
