### ISSUE TITLE
Crewmate version of Mad Guardian / マッドガーディアンの乗組員バージョン

### ISSUE THREAD

**Issue by SkullCreeper** [tukasa0001/TownOfHost#826]
English: We have madmate versions of Snitch and Crewmate. Mad Guardian does not have a crewmate equivalent. So why not add Guardian?

日本語：SnitchとCrewmateのマッドメイトバージョンがあります。 マッドガーディアンには乗組員に相当するものはありません。 では、Guardianを追加してみませんか？

**Comment by soukunsandesu** [comment]
I think it's too strong.

**Comment by shu-TownofHost** [comment]
I agree. However, if it is in a form that prevents a kill only once by completing the task and the kill is not exposed, it should be possible to implement from a balance standpoint.
