### ISSUE TITLE
BUG on v2.2.0

### ISSUE THREAD

**Issue by BornBasic** [tukasa0001/TownOfHost#827]
1. Chat got piled up with names in meeting when you are a ghost
2. Sheriff, Lighter, SabotageMaster & Crewmate randomly gets ShapeShifter button and sees other players with red names in meeting (see picture attached)
3. Jester wins but gets defeat screen, other sees impostors wins the game but not the Jester
4. Black screen when game starts and after a meeting forcing players to leave game
5. in Hide And Seek mode, can't see the impostor 

all bugs mentioned occurred in Android (for now) thank you

![291799278_429718292383791_3184176305547113691_n](https://user-images.githubusercontent.com/108614247/177041062-c5bfe2dd-2932-4add-a712-e8540fa16b30.jpg)

![Screenshot 2022-07-03 201042](https://user-images.githubusercontent.com/108614247/177039029-88f4f384-a34c-46fa-9814-5674e797deb4.jpg)

![291779933_1729247330760917_758588664082880537_n](https://user-images.githubusercontent.com/108614247/177038232-1b8ae3bb-d010-4cd9-b748-8e8f880a8edf.jpg)
![291341024_574945610762732_7458937517129966560_n](https://user-images.githubusercontent.com/108614247/177038233-af88818f-b2cb-4019-b962-c0d95be608f2.jpg)
![291124609_1076051719767669_3805956953643356166_n](https://user-images.githubusercontent.com/108614247/177038234-d2366a2a-d24c-45ce-bf72-89ac0bf20b1b.jpg)

**Comment by soukunsandesu** [comment]
``3. Jester wins but gets defeat screen, other sees impostors wins the game but not the Jester``
``4. Black screen when game starts and after a meeting forcing players to leave game``
``5. in Hide And Seek mode, can't see the impostor``
