### ISSUE TITLE
Few Bugs

### ISSUE THREAD

**Issue by Sh0kii** [tukasa0001/TownOfHost#828]
1. If a Dictator ends a vote while a Witch cursed a player, it will transfer the curse to the next round without killing the cursed player
~~2. 2.2.0 Ver. if host gets Sheriff, they will have an error after 30-ish seconds and will close the game completely~~
~~3. 2.2.0 Im adding the Cat and jester here for red names bug and Shapeshifting ability~~
~~4. Egoist is considered impostor side, however they do not win with impostor's. If an impostor is alive aswell as Egoist, the impostor will win solo, Egoist will show a Defeat screen, Egoist cannot kill impostors nor impostors can kill Egoist~~
~~5. Arsonist sometimes suicides as ghost multiple times~~
Edit:

~~6. Bait will not report impostor if Bait was Lover and they commit suicide due to other Lover being killed
Edit 2:~~
~~7. 2.2.0 Being Arsonist as a host also crashes the game after you try to douse a player~~
~~8. Vampire sometimes bugs his cooldown CD and has 0 Bite CD~~

**Comment by yurinakira** [comment]
`6.Bait will not report impostor if Bait was Lover and they commit suicide due to other Lover being killed`

This is not a bug.
I will notify you if bait is killed directly by impostor,
If your lover commits suicide, you will not be notified.

**Comment by Sh0kii** [comment]
> `6.Bait will not report impostor if Bait was Lover and they commit suicide due to other Lover being killed`
> 
> This is not a bug. I will notify you if bait is killed directly by impostor, If your lover commits suicide, you will not be notified.

I know that, what i ment to say is: If a player is a Lover with Bait player, when imps kill Bait's lover, it should report Bait's body, doesnt it?

**Comment by yurinakira** [comment]
![image](https://user-images.githubusercontent.com/84663668/177064224-3052a82f-83ca-49a8-80b4-27793c3c32be.png)
I'm translating, but I don't know if it's a letter.
Please explain with a picture.

**Comment by soukunsandesu** [comment]
```4.   Egoist is considered impostor side, however they do not win with impostor's. If an impostor is alive aswell as Egoist, the impostor will win solo, Egoist will show a Defeat screen, Egoist cannot kill impostors nor impostors can kill Egoist ```
This is a not bug.

**Comment by soukunsandesu** [comment]
``5. Arsonist sometimes suicides as ghost multiple times``
Specifications.

**Comment by soukunsandesu** [comment]
7. 2.2.0 Being Arsonist as a host also crashes the game after you try to douse a player
fixed

**Comment by Sh0kii** [comment]
> `5. Arsonist sometimes suicides as ghost multiple times` Specifications.

a player reported that as a sheriff kills him as being arsonist, he keeps dying after meetings as a ghost, its very rare that to occur, but it happends
