### ISSUE TITLE
Mod not starting

### ISSUE THREAD

**Issue by kushx1996** [tukasa0001/TownOfHost#832]
My mod started for one time but it is not starting now. It says a "Problem caused the program to stop working. Please close the program." I did not change anything in my PC but except for one time my mod is not working. Help please.
PS: I have both latest version of mod and AU.

**Comment by Sh0kii** [comment]
Make a fresh clean copy of the game and transfer the files from the mod into this new fresh copy, it will work :3

**Comment by soukunsandesu** [comment]
Maybe, it was fixed.
If you keep crashing, there is a problem on your side.
