### ISSUE TITLE
CRASHES and DISCONNECTS ALOT OF PLAYERS

### ISSUE THREAD

**Issue by TownOfGhost-AO** [tukasa0001/TownOfHost#834]
Hi, downloaded this mod last week worked fine apart from being laggy on my end as I am the host with said mod. 

Since the recent update, when loading into a game after pressing START the entire game shuts down and takes me back to my Desktop.

I've updated all drivers on my PC and still to no avail. 

- When can we see an ETA on bug fixes.

Thank you,
TownOfGhost-AO

**Comment by yurinakira** [comment]
翻訳
```
こんにちは、先週ダウンロードしたこのmodは、私がこのmodのホストであるため、私の側で遅れていることを除けば、うまく機能しました。

最近の更新以降、STARTを押した後にゲームにロードすると、ゲーム全体がシャットダウンし、デスクトップに戻ります。

PCのすべてのドライバーを更新しましたが、まだ役に立ちません。

バグ修正に関するリリース予定日はいつ表示されますか。
ありがとうございました、
TownOf Ghost -AO
```

**Comment by TownOfGhost-AO** [comment]
Any update? 
すべてのアップデート？

**Comment by TownOfGhost-AO** [comment]
![TOH - Fail](https://user-images.githubusercontent.com/108708575/177903826-c81a256b-0e3d-470f-80c7-531a2b9f7d45.jpg)

this is what happens, completely shuts down.

**Comment by soukunsandesu** [comment]
please wait next release!
we fixed it!
