### ISSUE TITLE
URGENT!!! CRASHES!!

### ISSUE THREAD

**Issue by TownOfGhost-AO** [tukasa0001/TownOfHost#849]
![TOH - Fail](https://user-images.githubusercontent.com/108708575/177905084-2b1ceff9-bcce-46af-b4d2-c26bf4380324.jpg)

I have a server where we play Town of Host and now we can't play... can we have an update on when we can see this issue resolved. please and thank you.

 @tukasa0001 @soukunsandesu @ykundesu @tanakanira0118 @tampopo-dandelion @shu-TownofHost

**Comment by soukunsandesu** [comment]
Maybe, we are already fixed.

**Comment by TownOfGhost-AO** [comment]
@soukunsandesu .. it's still happening, do you mean, its getting fixed in the next release? if so when will that be?

**Comment by TownOfGhost-AO** [comment]
It’s still not workin? When is the next release? Date?

**Comment by soukunsandesu** [comment]
Why Can't You Wait? Give me a little more time.
Mod development is not a job.
