### ISSUE TITLE
Few Bugs

### ISSUE THREAD

**Issue by TheKraze** [tukasa0001/TownOfHost#850]
There are a few glitches with the mod, but otherwise everything is great!

• When the host gets sheriff or arsonist, the game crashes.
•There’s a glitch that causes some people to see everyone’s name in red (They appear as an imposter [killing, shifting, sabotage, etc] whether they are or aren’t). After the first meeting ends, they become black screened.
•In some games, before the loading screen, some people get black screened.
•When the sheriff or arsonist dies, they continue to kill themself after every meeting ends.
•The kill cooldown resets to 0.1 when the mod crashes or a new lobby is created.    
•If you get lovers with the snitch role, you can’t see who imposters are after finishing tasks. 
•Sometimes sheriff and arsonist bugs on the loading screen and you can see who the other imposters are.
•As executioner, if your target leaves before dying your role won’t change and you stay executioner.

Thank you so much for your consideration and work with creating this mod!

**Comment by soukunsandesu** [comment]
``•The kill cooldown resets to 0.1 when the mod crashes or a new lobby is created.``
``•If you get lovers with the snitch role, you can’t see who imposters are after finishing tasks.``
``•Sometimes sheriff and arsonist bugs on the loading screen and you can see who the other imposters are.``
``•As executioner, if your target leaves before dying your role won’t change and you stay executioner.``
Already fixed in develop version.

**Comment by soukunsandesu** [comment]
``•When the sheriff or arsonist dies, they continue to kill themself after every meeting ends.``

Specifications.

**Comment by soukunsandesu** [comment]
•In some games, before the loading screen, some people get black screened.

Maybe, fixed in develop version

**Comment by TheKraze** [comment]
> 

Meeting will end, and you will be black screened for a few seconds, then the kill animation will show up (you kill yourself, the same animation when a player was bitten).

**Comment by taskmaster19** [comment]
Very comprehensive over of what I wanted to share about latest build myself. From the feedback of the group that I host a lobby for, can verify all of the above happens from time to time. Not mentioned but often found by us too:
- crew roles (like Bait, Mayor, Snitch, etc.) get an option to shapeshift / kill / vent from the start
- just visual: those who play in my lobby through the normal client, have players' names overlapping messages in ghost chat
- happened just once, not sure if it's connected directly with the mod: the player couldn't flip switches on the lights panel

That's about it. Great thanks for your effort and time developing this. Your work has given tons of fun and joy to so many people

**Comment by soukunsandesu** [comment]
> Meeting will end, and you will be black screened for a few seconds, then the kill animation will show up (you kill yourself, the same animation when a player was bitten).

This is a patch to remove black screen.

**Comment by soukunsandesu** [comment]
> Very comprehensive overview by the author of what I wanted to share myself. From the feedback of the group that I host a lobby for, can verify all of the above currently happens from time to time. Not mentioned but often found by us too:
> 
> * crew roles (like Bait, Mayor, Snitch, etc.) get an option to shapeshift / kill / vent from the start
> * just visual: those who play in my lobby through the normal client, have players' names overlapping messages in ghost chat (during meetings it becomes readable again)
> * happened just once, not sure if it's connected directly with the mod: the player couldn't flip switches on the lights panel
> 
> That's about it. Great thanks for your effort and time developing this. Your work has given tons of fun and joy to so many people

Can't fix it outside the meeting

**Comment by WartusTOH** [comment]
- As admin I have never gotten Witch, when playing with Vampire and Witch as imps. Vampire is first in the list, and my theory is, that admin only gets the first option in the list of imps. My last 15 games, where I have been the imposter, I got Vampire role. I dont know if it is a coincidence.

**Comment by WartusTOH** [comment]
Nevermind. I got it in my 20th try

**Comment by soukunsandesu** [comment]
Specifications.
