### ISSUE TITLE
Possibly Banned from making matches

### ISSUE THREAD

**Issue by camtheman807** [tukasa0001/TownOfHost#852]
This is a very weird occurrence, and I can't find any record of it anywhere, however it started after using the mod a few times.

Every time I try to create a match, it shows the "you've been kicked" message. Am I banned from creating matches? I have tried restarting, resetting the files, and re-downloading however nothing has worked. If I find a solution I will delete this post, but for now I am locked and I am desperately looking for a solution.

TYSM

![image](https://user-images.githubusercontent.com/108958391/178074175-98a449cf-d33b-4ffc-9b58-16a72d0b9521.png)

**Comment by camtheman807** [comment]
I Fixed it by going on an alt and leaving, no idea why, the bug should still be checked out tho

**Comment by soukunsandesu** [comment]
We have never received any such report. Do you have a log?

**Comment by soukunsandesu** [comment]
Closed because it doesn't confirm.
