### ISSUE TITLE
Role suggestion "Protector" 

### ISSUE THREAD

**Issue by Tommy-XL** [tukasa0001/TownOfHost#857]
This role protects a specific player in the vote, whether it be a traitor or a crew member (except neutral roles) also if the defender has a goal to protect a traitor, he will win with them, if the target is a crew member, then he will win with members  crew

**Comment by soukunsandesu** [comment]
Cannot cancel vote

**Comment by tampopo-dandelion** [comment]
弁護士的な感じかな？
