### ISSUE TITLE
Command Suggestion

### ISSUE THREAD

**Issue by AllawiEZ** [tukasa0001/TownOfHost#864]
Command: /role {RoleName}
Ability: When typing the command this will give you 100% the role you typed in.

Example: /role Egoist

When the game starts you will be 100% the Egoist.

**Comment by yurinakira** [comment]
翻訳

コマンド：/ role {RoleName}
能力：コマンドを入力すると、入力した役割が100％提供されます。

例：/ role Egoist

ゲームが始まると、100％エゴイストになります。

**Comment by yurinakira** [comment]
"/ role" There is no such chat command.
Not even systematically.
https://github.com/tukasa0001/TownOfHost/blob/main/README-EN.md#chat-commands


I tried it in my environment but it didn't happen.

The role percentage is not currently implemented on the lobby PC, so even 10% will be assigned 100%.


If there is no problem, close it

**Comment by soukunsandesu** [comment]
これ提案っす()

**Comment by yurinakira** [comment]
ああ、提案か、バグ報告かと思い込んでた()

**Comment by yurinakira** [comment]
ん－、、コマンドで役職設定するよりかは、csvかなんかで設定する方が使い勝手も管理も楽な気が...

**Comment by tampopo-dandelion** [comment]
採用します？

**Comment by yurinakira** [comment]
ん－裏でひっそりと試しでやってますが、
ちょっと気軽に入れる機能ではないと思うので(100%悪用されるので)色々検討してます。
まあどちらにせよこちらは閉じます。
