### ISSUE TITLE
Mare impostor bug and the Sheriff suicide bug and a bug with black screen of a sort when game started

### ISSUE THREAD

**Issue by Sh0kii** [tukasa0001/TownOfHost#865]
Mare has so far 2 bugs that i encountered today

1. Mare sometimes glitch out and their name shows as red in the meeting calls, still trying to figure out how it happends and what causes it(picture 1 circled in blue, the player was a Mare)
2. If Mare kills Trapper they wont be frozen in place, seems the speed boost from Mare overwrites the freeze from Trapper, this might be because Trapper is coded to set their killer's movement speed to 0 and that overlaps with the speed boost from Mare

~~Sheriff bug for ghost killing themselves as being sheriff (Picture 1, circled in red)~~

Game black screen(happend only once in around 30+ games, Picture 2)
![sadfgh](https://user-images.githubusercontent.com/108620138/178620882-1ee7055e-1f7d-4065-9a26-ac2c4cf76b38.jpg)
![sdfghj](https://user-images.githubusercontent.com/108620138/178620889-f330dc7d-bb3c-43bd-9fe7-765a41c54555.jpg)

**Comment by Sh0kii** [comment]
Edit:
Adding a new possible bug to Mare with Lovers
Lovers made Mare and another impostor be Lovers, is that possible and what even the odds for this?(check picture)
![fff](https://user-images.githubusercontent.com/108620138/178756675-3cffb724-1ace-47a2-8c2b-fbc2d7583950.jpg)

**Comment by Tommy-XL** [comment]
I confirm the bug with Sheriff, I had a round that Sheriff died in the first round and when I died, I started killing myself on the ghost and at the same time the player with the role of Sheriff said that he kills himself on the ghost several times

**Comment by soukunsandesu** [comment]
``Edit: This was on 2.2.0v , still have no idea if its possible on newest version.
Adding a new possible bug to Mare with Lovers
Lovers made Mare and another impostor be Lovers, is that possible and what even the odds for this?(check picture)``
Specifications.

**Comment by Sh0kii** [comment]
> `Edit: This was on 2.2.0v , still have no idea if its possible on newest version. Adding a new possible bug to Mare with Lovers Lovers made Mare and another impostor be Lovers, is that possible and what even the odds for this?(check picture)`
> 
> `I confirm the bug with Sheriff, I had a round that Sheriff died in the first round and when I died, I started killing myself on the ghost and at the same time the player with the role of Sheriff said that he kills himself on the ghost several times`
> 
> Specifications.

1. The Mare Lovers can be seen on the picture, 2 impostor roles are Lovers, this eather can't happend or its one in a million chance of happening. Never happend with any other impostor Roles, except the Mare. Might be due to mare is considered crewmember during normal lights and only impostor during lights out, i however cannot fully vouch for that if that is the case, thats just a suggestion on where to start looking for.
2. Sheriff seems to have a bug on mobile, where if they die, it sometimes makes them suicide as a ghost, meaning they got killed the game might make them kill themselves after every meeting, this so far only occured on mobile devices on my lobby.
Also, today a player said that he, as a sheriff can cause sabotages. I dont know if thats true, but investigation is in progress if that is somewhat of a case.

**Comment by Sh0kii** [comment]
> `Edit: This was on 2.2.0v , still have no idea if its possible on newest version. Adding a new possible bug to Mare with Lovers Lovers made Mare and another impostor be Lovers, is that possible and what even the odds for this?(check picture)`
> 
> Specifications.

2.2.1v Lovers again to 2 impostors, is that possible or its a bug?
picture below
![111111](https://user-images.githubusercontent.com/108620138/179045300-bdb68b5c-d87e-4a5c-ab5a-89aaefd920a7.jpg)

**Comment by Tommy-XL** [comment]
This is not a bug, Lovers can become both traitors and peaceful (and neutrals) just a mod from all players selects 2 random players and sometimes it happens that two traitors become lovers

**Comment by taskmaster19** [comment]
Support the comment above, we've gotten both Imposters being Lovers in our lobby several times (never playing with Mare)

**Comment by tampopo-dandelion** [comment]
Mareのキルにトラッパーを適応するか否か

**Comment by yurinakira** [comment]
>Mareのキルにトラッパーを適応するか否か

速度周りって"増減"ではなく代入(上書き)なので、今後修正する予定です。

**Comment by yurinakira** [comment]
そして恋人はランダムに割り当てられているだけなので、バグではないです。。。。
