### ISSUE TITLE
Imp suicide meeting bug

### ISSUE THREAD

**Issue by 1Cor1553** [tukasa0001/TownOfHost#866]
Sometimes all imps will suddenly kill themselves after meeting which immediately ends the game. There was no Dictator nor majority vote but we still received the shattered glass death screen, cause of death in result board will be displayed as "Kill" or "Fell" (Maybe Vamp or Shapeshifter role caused it?)

Perhaps you can look into this please? I'm looking forward to seeing your reply 
Thank you and have a nice day!

**Comment by soukunsandesu** [comment]
please dump and drop a log.

**Comment by soukunsandesu** [comment]
Closed because it doesn't confirm.
