### ISSUE TITLE
Suggestion: New Roles

### ISSUE THREAD

**Issue by Sh0kii** [tukasa0001/TownOfHost#868]
1. Zerg
2. Hunter

Zerg:
Backstory:
Zergs are alien race that live on unknown planet. They are shadowly creatures that do not like to stay on light for too long. Zergs are excellent killers that can parasite during lights, have the ability to take the form of someone else and kill during lights out.
Our crewmembers while traveling around the universe accidentally caught one Zerg unknowlingly and he infiltrated their ship as one of them.

Zerg abilities:
1. Shapeshift (during normal lights only)
2. Parasite(Zergling)(during normal lights only)
3. Eat(kill)(during lights out only)

Zerg explanation of abilities:
1. Shapeshift: can be used only when lights are not sabotaged
2. Parasite: they can bite someone and let them die on meetings if the Zerg is not exiled on meeting
3. Eat: can kill only if sabotage is called

Zerg explanation:
Zerg is a Neutral role, can kill all(including impostors), they win by themselves. Zerg can take the form of anyone during lights. Zergs cannot call any sabotages(Zergs will heavily rely on regular impostors to do it). Zergs can vent, they have normal movement speed even on lights out, their name does not show red when lights are out. Zergs can Parasite players on a long cooldown(60 seconds minimum), Parasite kills players during meetings if the Zerg is not exiled. Eat will be available only during lights sabotage. Bait role ofcourse will make the Zerg to self report. Zerg will have normal vision on lights and impostor vision during lights sabotage.

Hunter:
Backstory:
Hunter is a crewmate role that can place trackers on players to see what are they up to. Hunters will be a cruicial role for crewmates since they can track any player for certain amount of time, leaving a trail under the tracked unit, giving vision on the tracked unit on the map.

Hunter Abilities:
1. Track
2. Higher vision then normal crewmembers
3. Kill button on Tracked unit

Hunter explanation of abilities:
1. Track: Tracking a player will show where they are on map, leaving a trail under the tracked unit, for X amount of seconds(seconds are made in settings)
2. High vision: Hunters will have higher vision then normal crewmates(amount of vision is set in settings)
3. Kill: Hunters will have the ability to kill a tracked unit, only during Track. A success kill is triggered only for impostors or jester. Any other role will make the Hunter suicide(if that is possible, ofcourse)

------------------------------------------------------------------------
Sidenote:
Doctor and Bait
1. Doctor: Doctor will be able to see how they died
1.1. Zerg:
1.1.1. Parasited
1.1.2. Eaten
1.2. Hunter:
1.2.1. Tracked
1.2.2. Misfire
2. Bait:
2.1. Bait will self report on Zerg while they die from Eat

------------------------------------------
The roles will be fun to play and its a new idea. No modded games have these roles.

Regards, Sh0kii

**Comment by soukunsandesu** [comment]
Please create issues one by one

**Comment by yurinakira** [comment]
Also give the title a role name

**Comment by tampopo-dandelion** [comment]
jackalと同じような理由でできなそうだと思うのですがどうですかね？
トラッカーは頑張ればできるかも？
