### ISSUE TITLE
Bug? Dictator - Player cursed

### ISSUE THREAD

**Issue by WartusTOH** [tukasa0001/TownOfHost#871]
Hello.

I have exprienced a few times, when the dictator missfires at the Witch, if a player is cursed. The cursed player survives the vote anyway and turns up alive in next round. In the next meeting they are still cursed, and will die, if the Witch isnt killed in the 2nd meeting.
Hope it makes sense.

Wartus

**Comment by WartusTOH** [comment]
Still have problems with the Vampire killcooldown being 0.1 sec suddently

**Comment by soukunsandesu** [comment]
Please dump and drop a log.

**Comment by yurinakira** [comment]
応答ないんでClose
