### ISSUE TITLE
2 Executioners and 2 Opportunist Wins together, despite there only being 1 for each.

### ISSUE THREAD

**Issue by music-discussion** [tukasa0001/TownOfHost#879]
![image](https://user-images.githubusercontent.com/80537729/179133178-fb154440-19f3-45c5-96b2-22315417c696.png)

The picture displays it all.

**Comment by yurinakira** [comment]
Thank you for reporting the bug.
If any of "Opportunist", "SchrodingerCat", and "Executioner" are present at the same time, the text seems to be strange.
It does not affect play.
It will be fixed in the next release.

**Comment by yurinakira** [comment]
A fix has been made in the development version.
It will be resolved at the next release.
