### ISSUE TITLE
Shapeshifter glitch ban

### ISSUE THREAD

**Issue by 1Cor1553** [tukasa0001/TownOfHost#881]
Any shapeshifter role related will be kicked from the game if they perform the 2nd shapeshift in the same round, essentially a huge nerf for shapemaster and fireworks. 
ss->ss = Banned
Ss -> meeting -> ss = Not banned
Hope you can look more into it, thank you

**Comment by tampopo-dandelion** [comment]
did you set vanilla shapeshifter cooldown to zero?
if you did not,it is the cause.
and at the next time, please ask us in our discord server.

**Comment by yurinakira** [comment]
リリースノートに注意文記載しました。
