### ISSUE TITLE
SpeedBooster

### ISSUE THREAD

**Issue by AllawiEZ** [tukasa0001/TownOfHost#891]
Speed booster doesn't work even if you finish all of your tasks.

**Comment by yurinakira** [comment]
Please log it.  
Also, the speed booster speeds up the legs of random targets, so please check that as well.

**Comment by AllawiEZ** [comment]
> Please log it.  
> Also, the speed booster speeds up the legs of random targets, so please check that as well.

1- How do i log it?
2- I turned on no game end setting and played with another account 2/15. And i finished my tasks as speed booster not me or the other account got the speed boost, Also i made when speed booster finishes tasks he gives 3x speed and still tie.

**Comment by Tommy-XL** [comment]
I confirm this role does not work on version 2.2.1
