### ISSUE TITLE
Suggestion: New Role Idea (someone on discord suggested it)

### ISSUE THREAD

**Issue by music-discussion** [tukasa0001/TownOfHost#895]
Role Idea: Silencer

Role Info: Silence others in Meetings.

Role Command Info: (Impostors): The first killing attempt silences the crewmate. Silencing the crewmate will prevent them from talking in the next meeting. After Silencing, they are now a regular Impostor/Shapeshifter. (Silenced crewmates will have something next to their name to show that they can't talk.)

Role Lore: Supposedly they were bullied back in the day. Eventually, they came across a prank that could get the bullies arrested. Wanting revenge, they tried snitching, but no one listened. The bully attempted, and everyone believed him. Now, no one wanted to do anything. Depressed, he almost took his own life. Instead, he sided with the dark side. Now, he uses the tricks the bullies taught him on the crewmates to make sure he isn't alone.

How this Role Works: The Impostors Kill Button is at first their Silence Button. Clicking this button will do the GA protect thing, letting you know that person is now silenced. After hearing that, they are now a regular Impostor. Their Kill CD is now what settings they chose. Whoever player they attempted to kill are now muted for the next meeting. After the next meeting, they are unmuted. And the cycle starts over again.

![image](https://user-images.githubusercontent.com/80537729/179425326-2c34aef3-ff5f-4726-baea-7c437e7f2bb5.png)

Please tell me if there is anything I should add!

### Silencer Options
| Name | Description | Type | Default |
|----------|:-------------:|:------:|:------:|
| Silencer | The percentage probability of the Silencer appearing | Percentage | 0% |
| Maximum | How Many Silencers can appear | Int | 1 |
| Initial Silence Cooldown | The initial cooldown of the Silencer's Silence Button | Time | 10s |
| What Happens After Silence | What the Kill Cooldown is after Silence | Array[Immediate Option to Kill, Kill CD - Silence CD, From Kill CD, Custom | From Kill Cooldown |
| Custom KIll CD After Silence | Custom Kill Cooldown after Silence (if option is selected from above) | Int | 25 |

**Comment by AllawiEZ** [comment]
Very lovely idea but you cannot delete chat messages...... or he will be stuck on please wait 2 second before typing again

**Comment by yurinakira** [comment]
This proposal has been rejected in the past because VCs such as Discord cannot be silenced.
