### ISSUE TITLE
AirshipでTerroristが有効時、プレイヤーを追放すると会議終了後の暗転が戻らない

### ISSUE THREAD

**Issue by tukasa0001** [tukasa0001/TownOfHost#9]
tukasa0001の環境では再現できず、現時点で謎のままです。
情報があればだれでもいいのでください！

**Comment by MASA0063** [comment]
Among usの本体がv2022.2.24sで、Town of Host v1.4b #3の環境ですが、テロリストの有効無効に関わらず、Airshipでプレイヤーを追放すると会議終了後に、湧き場所の選択も出ず、暗転して戻らなくなります（サウンドは鳴っていますが、操作もできない模様で、フリープレイでも再現できます）。
オンラインプレイでそのまま放置した場合、その後、会議に入っても画面が暗転したままで、会議が終わったときにまた別の誰か(Bとする)が追放されると、最初に追放された人(Aとする)の「Aが追放された」という表示の上に、「Bが追放された」という表示が重なって出てきます。人が追放されるたびに文字が重なっていきます。その後、試合が終わっても、画面が変わらないため、部屋を抜けるしかない状態になります。
（暗転した画面で右上の歯車マークがある辺りをクリックすると、設定メニューは開くので、部屋から抜けることはできます）
設定・言語・プレイヤースキン・プレイヤーネーム等、諸々変更を試してフリープレイで検証してみましたが、解決できませんでした。
人によってはMODを導入してもこのような現象は起きていませんが、私の知ってる範囲で三人に同じ現象が発生しているため、再現性のあるバグなのかなと考えております。
その他、必要な情報がありましたら提示いたしますので、MOD開発の一助になりましたら幸いです。(_ _)

**Comment by tukasa0001** [comment]
#3はまた別の原因でそのバグが発生していて、次のバージョンで修正されます。

**Comment by Palpunte-Soukun** [comment]
こちらの問題はどうなりましたか？

**Comment by MASA0063** [comment]
＃5にて、Airshipでの追放後も正常に動くようになりました。(_ _)
