### ISSUE TITLE
Guesser role suggestion

### ISSUE THREAD

**Issue by Gurge44** [tukasa0001/TownOfHost#900]
Hey! I have a good role idea to add... It is the Evil Guesser / Nice Guesser / Assassin, or whatever you want to call it. This role could guess other players' roles in meetings. If the guesser is correct about the player's role, the player dies in the meeting. If the guesser is wrong about their role, the guesser dies in the meeting.
Now, I know this would be hard to code since it has to work with the base game too, but it's such a needed role to stop people from claiming roles. And I believe in the devs, you can do it!
This role is also in TheOtherRoles, or TownOfHost, so you can check that if it helps.
Hope you will consider adding this role, but if not, it's still a good mod!

**Comment by Tommy-XL** [comment]
I already suggested this role and I was told that the role is already being created, but it is not clear how soon this role will be added to the mod (I hope the mod developer below will answer me)

**Comment by soukunsandesu** [comment]
What is this role "Assassin"?

**Comment by soukunsandesu** [comment]
I mistakenly thought it was Assassin in ExtremeRoles.

**Comment by tampopo-dandelion** [comment]
> I already suggested this role and I was told that the role is already being created, but it is not clear how soon this role will be added to the mod (I hope the mod developer below will answer me)

we must fix bug first, but there are many bugs in our mod.
honestly,we cannot answer when guesser can be released .sorry please just wait.
