### ISSUE TITLE
Gamemode Suggestion "Battle Royal"

### ISSUE THREAD

**Issue by AllawiEZ** [tukasa0001/TownOfHost#902]
Gamemode: Battle Royal

Player with Town Of Host mod loading screen: BATTLE ROYAL
with description "Kill other players!"

Players without Town Of Host mod loading screen: Impostor

Additional settings:
vents: ON/OFF
Admin table: ON/OFF
Security Cameras: ON/OFF
Vitals: ON/OFF
Logs on Mira HQ: ON/OFF
Teams: ON/OFF
With Teams ON
-Allow teammates to kill each other: ON/OFF
-Get an arrow pointing at your teammate: ON/OFF

**Comment by yurinakira** [comment]
reject close issue
