### ISSUE TITLE
Suggestion - setting to change post-spawn kill cooldown

### ISSUE THREAD

**Issue by taskmaster19** [tukasa0001/TownOfHost#905]
Sorry, can't find where it is possible to contact you on your Discord server

Wanted to ask if it's possible to add a setting for increasing (or lowering) the short kill cooldown that Imposters have from the start of the first round in the game
Thank you

**Comment by yurinakira** [comment]
https://discord.com/channels/931559416413687848/995761451102904500
#help Ask a question here.

**Comment by yurinakira** [comment]
Anser.
Implementation is possible.

**Comment by yurinakira** [comment]
[SelfMemo]
実装は可能だが、沸きタイミング周りはとても面倒で複雑なので実装する予定はなし
