### ISSUE TITLE
Lovers bug with host

### ISSUE THREAD

**Issue by The3headedNinja** [tukasa0001/TownOfHost#908]
The lovers role is really weird whenever im the lover as host for example loving mayor i cannot do tasks which ruins some roles such a snitch who need to do tasks but with mad snitch u can do tasks with the lover role

**Comment by soukunsandesu** [comment]
https://github.com/tukasa0001/TownOfHost/issues/903

**Comment by yurinakira** [comment]
@The3headedNinja 
Crew camp + Lovers have not assigned any tasks. It's a specification, not a bug.
