### ISSUE TITLE
Black screen problem

### ISSUE THREAD

**Issue by Tommy-XL** [tukasa0001/TownOfHost#915]
When the round starts and the round is loading and someone crashes due to an error, then a black screen occurs for some people, I don’t know why this happens

**Comment by Tommy-XL** [comment]
I closed my last question because it was not related to the "Airship map

**Comment by Tommy-XL** [comment]
[LogOutput.log](https://github.com/tukasa0001/TownOfHost/files/9168322/LogOutput.log)

**Comment by soukunsandesu** [comment]
https://github.com/tukasa0001/TownOfHost/issues/903
