### ISSUE TITLE
Can you teach me how to compile this mod 

### ISSUE THREAD

**Issue by bilibili-bidge** [tukasa0001/TownOfHost#924]
When I was sinoifying the mod of town of host Encountered a problem: git did not download the problem. 
I know the function of GIT, but I downloaded GIT. This widens the scope of the error 
(it may be my problem. I can't open git's official website, because in China, GIT's official website is a foreign server) 
After I downloaded it, there was a problem that the variable was not found.
Can you teach me how to compile this mod 
(sorry, discord is inaccessible in China) (I compiled it with dotnet)

**Comment by yurinakira** [comment]
I don't teach how to compile to prevent fraudulent reasons.
