### ISSUE TITLE
Apply Our Chinese translate

### ISSUE THREAD

**Issue by JieGeLovesDengDuaLang** [tukasa0001/TownOfHost#942]
Hello.
Recently, your mod(Town Of Host) is very popular in China.
But, there is an issue that increases the difficulty of playing this mod, the problem is: no translation!
This will add a lot of inconvenience.
We hope more people can play this mod normally, so we translated this mod.
and we hope you can add Chinese translation.
[TownOfHost.Resources.string.csv](https://github.com/tukasa0001/TownOfHost/files/9225405/TownOfHost.Resources.string.csv)

Thank you very much.

**Comment by tampopo-dandelion** [comment]
Please do not use the issue. Please contact discord if you need anything.

**Comment by JieGeLovesDengDuaLang** [comment]
but...
in China can not use discord...
I'll try it.

**Comment by yurinakira** [comment]
I have received the csv from another person.
We will apply them.
