### ISSUE TITLE
Application for Simplyfied Chinese Translation

### ISSUE THREAD

**Issue by ZeMingoh233** [tukasa0001/TownOfHost#943]
Hi there. I'm Zeming, an amateur Chinese translator subordinate to 4H sinicization group. 
We've translated many modules of among us to Chinese such as The Other Roles GM, Las Monjas and Nebula. 
Recently Town of Host set off an upsurge in China, as a result we managed to complete the Chinese translation of the mod and here I am to ask whether you would like to apply our translation to your mod or not. 
The work is already done two weeks ago, but we encounter some problems while editing the strings so we have to contact you after such a long time. 
It's of great honour if you accept our translation.
[TownOfHost.Resources.string.csv](https://github.com/tukasa0001/TownOfHost/files/9225443/TownOfHost.Resources.string.csv)

**Comment by fivefirex** [comment]
Hi, I'm FiveFireX,  an Chinese translator subordinate to 4H sinicization group too.
As Zeming say, we already translate a lot of mods before. Our GitHub org is at [here](https://github.com/4H-Developers) and website is at [here](https://amonguscn.club/). We can give you long term translate support. We will also guarantee to the quality.
The mods like The Other Roles, Las Monjas need the host and the members both install the mods. It is very difficult and not friendly to install mods for new members.
But Town Of Host is magic! It means the new members will no longer install the mods difficulty. They have only to click on the buttons.
So we translate it into SChinese. We want more and more friends to play Town Of Host. It is an honor if you accept our translation.
Thanks!
