### ISSUE TITLE
(Bug?) Killing Witch as Sheriff, but cursed player still dies

### ISSUE THREAD

**Issue by W1GZY** [tukasa0001/TownOfHost#976]
As Sheriff, you can kill the witch, but if witch has cursed someone that round before dying, that cursed player will join the meeting cursed and die at the end of the meeting. 
Cursed player has no option but to die because there is no witch to kick out.

Curse should be lifted if the witch dies of other reasons even though he is not kicked out.

**Comment by yurinakira** [comment]
Specifications.

**Comment by W1GZY** [comment]
1. Witch curses player A 2. Sheriff kills Witch 3. Meeting happens 4. Player A is still cursed 5. Witch is already dead because Sheriff killed him 6. Meeting ends 7. Player A dies because he is still cursed even though Sheriff killed him

What exactly are you looking for?
