### ISSUE TITLE
Bug about game translation

### ISSUE THREAD

**Issue by MC-AS-Huier** [tukasa0001/TownOfHost#978]
I tried to compile the source code in the development branch, but the professional translation in the lobby is not displayed after Among Us is installed in TownOfHost, and the professional translation in the game is not displayed either
![B{9`RO$Y550HZ6HSF0E$P6L](https://user-images.githubusercontent.com/107238739/183247995-2c7c7cd1-080f-4e82-a1b0-248152c7084a.png)
.

**Comment by yurinakira** [comment]
thanks reported.
fixed
https://github.com/tukasa0001/TownOfHost/pull/979/files
