### ISSUE TITLE
(Suggestion) add a .txt file of banned players

### ISSUE THREAD

**Issue by W1GZY** [tukasa0001/TownOfHost#980]
After hosting few games, I found out that there is some people that I dont want in my lobby for different reasons.
My suggestion is that we get a banned.txt file where we can write down Among us ID (example: snitchysnitch#4837) and if the ID mentioned in the .txt files joins our lobby, their name turn light red (just like how TOH users turn light blue) so we can easily identify those players.

**Comment by yurinakira** [comment]
We also proposed that feature, but it was rejected.
