### ISSUE TITLE
ask some questions

### ISSUE THREAD

**Issue by MC-AS-Huier** [tukasa0001/TownOfHost#996]
I'm not a member of the "四个憨批汉化组", I'm just a person who wants to contribute to the SChinese translation. If the SChinese translation of this project is exclusively in charge of the "四个憨批汉化组", then I am very sorry
（私は「フォーナンブ中国化グループ」のメンバーではありません, 私はただの中国語翻訳に貢献したい人です. このプロジェクトの中国語翻訳は、「フォーナンパイ中国化チーム」が独占的に担当している場合. 、それでは大変申し訳ありません）

**Comment by NetherDragonTw** [comment]
能否使用中文? 我或許可以幫到你 我或許知道先前簡體中文翻譯的一些事

**Comment by MC-AS-Huier** [comment]
> 能否使用中文?我或許可以幫到你 我或許知道先前簡體中文翻譯的一些事
只是我和四個憨批漢化組對於簡體中文的漢化產生了糾紛，不知道簡體中文漢化是四個憨批獨占還是，所有人都可以參與

**Comment by NetherDragonTw** [comment]
> > 只是我和四個憨批漢化組對於簡體中文的漢化產生了糾紛，不知道簡體中文漢化是四個憨批獨占還是，所有人都可以參與

原來如此, 但是TOH官方沒有明確標示, 我以前做潛艇翻譯時他們好像沒有這個規定, 所以我推翻了上一版的翻譯

**Comment by NetherDragonTw** [comment]
> > 能否使用中文?我或許可以幫到你 我或許知道先前簡體中文翻譯的一些事
> > 只是我和四個憨批漢化組對於簡體中文的漢化產生了糾紛，不知道簡體中文漢化是四個憨批獨占還是，所有人都可以參與

忘了說阿, 你的標題要改成"ask some questions"

**Comment by yurinakira** [comment]
Please close when you come to a conclusion
